### ISSUE TITLE
jeKnowledge logo disappears from footer

### ISSUE THREAD

**Issue by teresalazar13** [jeKnowledge/the-grad-list-v2#2]

**Comment by mikeevmm** [comment]
Where is the logo added?

**Comment by mikeevmm** [comment]
Also, under any specific situation?

**Comment by pedrocaseiro** [comment]
@mikeevmm after some playing around I only noticed this bug happening when you click on the word "jeKnowledge" next to the footer and after that coming back to "The Grad List" page. One solution is making the "jeKnowledge" open on a new tab I think.

Edit: It also happens when you share a post. My conclusion is that it happens everytime you change to a non grad list url and you try to come back after that

**Comment by mikeevmm** [comment]
@pedrocaseiro Perhaps the logo is being added on the wrong trigger; coming back from another page does not add the logo. If that's the case, we could fix it by changing where the logo is added.

**Comment by teresalazar13** [comment]
The logo is added i Client/templates/includes - footer. It is in the Public folder @mikeevmm

**Comment by jbernardo95** [comment]
@pedrocaseiro Fixed ?

**Comment by pedrocaseiro** [comment]
@jbernardo95 not yet

**Comment by pedrocaseiro** [comment]
@jbernardo95 Ok it partially fixed it. It is still disappearing when you refresh the page. The problem is what @mikeevmm mentioned, a trigger problem. @teresalazar13 this is probably the same bug happening with the logo

**Comment by pedrocaseiro** [comment]
@mariamargarida can you check it?

**Comment by jbernardo95** [comment]
@teresalazar13 @pedrocaseiro review pls ^

**Comment by teresalazar13** [comment]
still not working when I refreshing page in somes pages. It works when the page is refreshed in the home page @jbernardo95 @pedrocaseiro

**Comment by jbernardo95** [comment]
@teresalazar13 I am 99% sure the latest version of the code is not deployed, that's why the bug is still there.
Please check that and let me know 🙂

**Comment by teresalazar13** [comment]
yes, it is fixed! thanks
